spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: null
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  server:
    port: 8080
